plugins {
    id 'eclipse'
    id 'idea'
    id 'net.fabricmc.fabric-loom' version '1.15.5'
}

version = project.mod_version
group = project.maven_group
base {
    archivesName.set(project.archives_base_name)
}

loom {
    splitEnvironmentSourceSets()
    accessWidenerPath = file("src/main/resources/kaleidoscope_cookery.accesswidener")

    mods {
        "kaleidoscope_cookery" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

fabricApi {
    configureDataGeneration {
        outputDirectory.set(file("src/main/generated"))
        addToResources.set(true)
    }

    configureTests {
        createSourceSet.set(true)
        modId.set("kaleidoscope_cookery_gametest")
        enableClientGameTests.set(false)
    }
}

repositories {
    maven { url = "https://maven.shedaniel.me" }
    exclusiveContent {
        forRepository {
            maven {
                url = "https://cursemaven.com/"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        // location of the maven that hosts JEI files since January 2023
        // Patchouli
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    clientCompileOnly "mezz.jei:jei-${project.minecraft_version}-common-api:${project.jei_version}"
    clientCompileOnly "mezz.jei:jei-${project.minecraft_version}-fabric-api:${project.jei_version}"
    compileOnly "maven.modrinth:jade:${project.jade_version}"
    clientCompileOnly "maven.modrinth:rei:${project.rei_version}"
    clientCompileOnly "maven.modrinth:architectury-api:${project.architectury_version}"
    clientCompileOnly "maven.modrinth:cloth-config:${project.cloth_config_version}"
    clientCompileOnly "me.shedaniel.cloth:basic-math:${project.basic_math_version}"
}

def modVersion = project.version
def minecraftVersion = project.minecraft_version
def loaderVersion = project.loader_version
def fabricVersion = project.fabric_version

processResources {
    inputs.property "version", modVersion
    inputs.property "minecraft_version", minecraftVersion
    inputs.property "loader_version", loaderVersion
    inputs.property "fabric_version", fabricVersion
    filteringCharset = "UTF-8"

    filesMatching("fabric.mod.json") {
        expand(
                "version": modVersion,
                "minecraft_version": minecraftVersion,
                "loader_version": loaderVersion,
                "fabric_version": fabricVersion
        )
    }
}

def targetJavaVersion = 25
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    sourceCompatibility = JavaVersion.toVersion(targetJavaVersion)
    targetCompatibility = JavaVersion.toVersion(targetJavaVersion)
    toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    withSourcesJar()
}
