org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=26.2
loader_version=0.19.3

mod_version=1.1.0.8-fabric+mc26.2
maven_group=com.github.ysbbbbbb
archives_base_name=kaleidoscopecookery

fabric_version=0.153.0+26.2
farmers_delight_version=26.2-3.6.8
farmers_delight_sha256=cad661340de553b74e1a332d989a09208358666187ff876dabc75abad590118f
jei_version=30.11.0.67
jade_version=26.2.9+fabric
wthit_version=20.0.0
wthit_api_sha256=1056477e0ac7e9fc1882422927cb795f905038fc784fd3f8be70dd5914e81138
badpackets_version=0.12.2
rei_version=26.2.820+fabric
architectury_version=21.0.4+fabric
basic_math_version=0.6.1
